# weekly batch-job.yml
name : Weekly Batch Job

on:
  schedule:
    - cron : '0 0 * * 0'
    
jobs:
  fetch-APT:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch URL
        uses: boyeborg/fetch-url-action@v1.1
        with:
          url: https://myhome-apply.vercel.app/api/refresh?category=APT
          run: echo "run the apt"
      - name: backup logging
        if: ${{ failure() }}
        run: echo backup APT
  sleep:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'
  fetch-NonApt:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch URL
        uses: boyeborg/fetch-url-action@v1.1
        with:
          url: https://myhome-apply.vercel.app/api/refresh?category=NonApt
          run: echo "run the NonApt"
      - name: backup logging
        if: ${{ failure() }}
        run: echo backup NonApt 
  sleep-step:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'
  fetch-Remain:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch URL
        uses: boyeborg/fetch-url-action@v1.1
        with:
          url: https://myhome-apply.vercel.app/api/refresh?category=Remain
          run: echo "run the Remain"
      - name: backup logging
        if: ${{ failure() }}
        run: echo backup Remain 
  weekly-report:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger weekly report
        uses: boyeborg/fetch-url-action@v1.1
        with:
          url: https://myhome-apply.vercel.app/api/report/weekly?category=APT
          run: echo "run weekly report"
      - name: backup logging
        if: ${{ failure() }}
        run: echo backup weekly report
